# Домашнее задание по теме: пакет `pandas` (основная информация)

## Подготовка окружения

In [3]:
# ВНИМАНИЕ: необходимо удостовериться, что виртуальная среда выбрана правильно!

# Для MacOS/Ubuntu
# !which pip

# Для Windows
# !where pip

C:\Users\Public\Anaconda3\envs\levelup_ds\Scripts\pip.exe

In [4]:
# !conda install pandas -y

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\Public\Anaconda3\envs\levelup_ds

  added / updated specs:
    - pandas


The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  bottleneck         pkgs/main/win-64::bottleneck-1.3.2-py39h7cc1a96_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2021.3.0-haa95532_3372
  mkl                pkgs/main/win-64::mkl-2021.3.0-haa95532_524
  mkl-service        pkgs/main/win-64::mkl-service-2.4.0-py39h2bbff1b_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.3.0-py39h277e83a_2
  mkl_random         pkgs/main/win-64::mkl_random-1.2.2-py39hf11a4ad_0
  numexpr            pkgs/main/win-64::numexpr-2.7.3-py39hb80d3ca_1
  numpy              pkgs/main/win-64::numpy-1.20.3-py39ha4e8547_0
  numpy-base         pkgs/main/win-64::numpy-base-1.20.3-py39hc2deb75_0
  pandas             pkgs/main/win-64::pandas-1.3.0-py39hd77b12b_0


Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

==> WARNING: A newer version of conda exists. <==
  current version: 4.10.1
  latest version: 4.10.3

Please update conda by running

    $ conda update -n base -c defaults conda

In [5]:
import pandas as pd

pd.__version__

'1.3.0'

## Загрузка и изучение данных

In [7]:
wiki_page = "https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D1%8F%D0%B7%D1%8B%D0%BA%D0%BE%D0%B2_%D0%BF%D0%BE_%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D1%83_%D0%BD%D0%BE%D1%81%D0%B8%D1%82%D0%B5%D0%BB%D0%B5%D0%B9"

In [10]:
# прочитать данные из указанной wiki страницы с помощью `pandas`
# ВНИМАНИЕ: при чтении указать номер колонки с индексом = 0
df_from_wiki_page = pd.read_html(wiki_page)
display(df_from_wiki_page[0])

,№,Язык,Родной язык по версии Ethnologue[1],Основная страна,Количество стран
0,1,Китайский,1 296 461 000[2] — 1 311 000 000,Китай,39
1,2,Испанский,460 000 000,Испания,31
2,3,Английский,379 000 000,Великобритания,137
3,4,Хинди,341 000 000,Индия,4
4,5,Арабский,313 177 600[3] — 319 000 000,Саудовская Аравия,59
5,6,Бенгальский,228 000 000,Бангладеш,4
6,7,Португальский,221 000 000,Португалия,15
7,8,Русский,154 000 000,Россия,19
8,9,Японский,128 000 000,Япония,2
9,10,Лахнда (Западный панджаби),119 000 000,Пакистан,6
10,11,Маратхи,83 100 000,Индия,1
11,12,Телугу,82 000 000,Индия,2
12,13,Малайский,80 300 000,Малайзия,20
13,14,Турецкий,79 400 000,Турция,8
14,15,Корейский,77 300 000,Корея,6
15,16,Французский,77 200 000,Франция,54
16,17,Немецкий,76 100 000,Германия,28
17,18,Вьетнамский,76 000 000,Вьетнам,4
18,19,Тамильский,75 000 000,Индия,7
19,20,Урду,68 600 000,Пакистан,7
20,21,Яванский,68 300 000,Индонезия,3
21,22,Итальянский,64 800 000,Италия,14
22,23,Персидский,61 800 000,Иран,30
23,24,Гуджарати,56 400 000,Индия,7

In [12]:
# отобразить все прочитанные таблицы с веб-страницы
for index, df_from_page in enumerate(df_from_wiki_page):
    print(f"index = {index}")
    display(df_from_page)

index = 0

,№,Язык,Родной язык по версии Ethnologue[1],Основная страна,Количество стран
0,1,Китайский,1 296 461 000[2] — 1 311 000 000,Китай,39
1,2,Испанский,460 000 000,Испания,31
2,3,Английский,379 000 000,Великобритания,137
3,4,Хинди,341 000 000,Индия,4
4,5,Арабский,313 177 600[3] — 319 000 000,Саудовская Аравия,59
5,6,Бенгальский,228 000 000,Бангладеш,4
6,7,Португальский,221 000 000,Португалия,15
7,8,Русский,154 000 000,Россия,19
8,9,Японский,128 000 000,Япония,2
9,10,Лахнда (Западный панджаби),119 000 000,Пакистан,6
10,11,Маратхи,83 100 000,Индия,1
11,12,Телугу,82 000 000,Индия,2
12,13,Малайский,80 300 000,Малайзия,20
13,14,Турецкий,79 400 000,Турция,8
14,15,Корейский,77 300 000,Корея,6
15,16,Французский,77 200 000,Франция,54
16,17,Немецкий,76 100 000,Германия,28
17,18,Вьетнамский,76 000 000,Вьетнам,4
18,19,Тамильский,75 000 000,Индия,7
19,20,Урду,68 600 000,Пакистан,7
20,21,Яванский,68 300 000,Индонезия,3
21,22,Итальянский,64 800 000,Италия,14
22,23,Персидский,61 800 000,Иран,30
23,24,Гуджарати,56 400 000,Индия,7

index = 1

,№,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
0,1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"
1,2,Арабский,422 039 637,NaN,"страны Северной Африки, Саудовская Аравия, Ира...",العربية
2,3,Хинди,366 000 000,Индия,Индия,हिन्दी
3,4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая ...",English
4,5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Сурина...","Español, Castellano"
...,...,...,...,...,...,...
63,65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
64,66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"
65,67,Дакхни[en],10 709 800,Индия,Индия,NaN
66,68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy
67,69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова

In [13]:
# получить dataframe с таблицей "Данные энциклопедии Encarta 2009 года"
df_from_wiki_page[1]

,№,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
0,1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"
1,2,Арабский,422 039 637,NaN,"страны Северной Африки, Саудовская Аравия, Ира...",العربية
2,3,Хинди,366 000 000,Индия,Индия,हिन्दी
3,4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая ...",English
4,5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Сурина...","Español, Castellano"
...,...,...,...,...,...,...
63,65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
64,66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"
65,67,Дакхни[en],10 709 800,Индия,Индия,NaN
66,68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy
67,69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова

In [16]:
# сохранить dataframe с таблицей "Данные энциклопедии Encarta 2009 года" в csv
df_from_wiki_page[1].to_csv('data_Encarta_2009.csv')

In [20]:
# вывести первые 20 строк
df_2009 = pd.read_csv('data_Encarta_2009.csv', index_col=0)
df_2009.head(20)

,№,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
0,1,Китайский,1 212 560 000,Китай,"Китай, Тайвань, Сингапур, Малайзия","中文, 汉语"
1,2,Арабский,422 039 637,NaN,"страны Северной Африки, Саудовская Аравия, Ира...",العربية
2,3,Хинди,366 000 000,Индия,Индия,हिन्दी
3,4,Английский,341 000 000,Англия,"Великобритания, США, Канада, Австралия, Новая ...",English
4,5,Испанский,322 200 637,Испания,"Испания, Южная Америка (кроме Бразилии, Сурина...","Español, Castellano"
5,6,Бенгальский,207 000 000,Бенгалия,"Бангладеш, Индия",বাংলা Bāṇlā
6,7,Португальский,176 000 000,Португалия,"Португалия, Ангола, Бразилия, Гвинея-Бисау, Ка...",Português
7,8,Русский,167 000 000,Россия,"Россия, Украина, Казахстан, Белоруссия, Литва,...",Русский язык
8,9,Японский,125 000 000,Япония,Япония,日本語
9,10,Немецкий,100 130 000,Германия,"Германия, Австрия, Швейцария, Люксембург, Лихт...",Deutsch
10,11,Корейский,78 000 000,Корея,"Республика Корея, КНДР, КНР, США, Япония","한국어, 조선말"
11,12,Французский,78 000 000,Франция,"Франция, Монако, Люксембург, Бельгия, Швейцари...",Français
12,13,Яванский,75 567 550,Индонезия,Индонезия,"Basa Jawa, Basa Jawi"
13,14,Телугу,69 666 000,Индия,Индия,తెలుగు
14,15,Маратхи,68 022 000,Индия,Индия,मराठी
15,16,Вьетнамский,68 000 000,Вьетнам,"Вьетнам, США, Камбоджа, Франция",Tiếng Việt
16,17,Тамильский,66 000 000,Индия,"Индия, Шри-Ланка, Сингапур, Малайзия",தமிழ்
17,18,Итальянский,62 000 000,Италия,"Италия, Сан-Марино, Ватикан, Швейцария (Тичино)",Italiano
18,19,Турецкий,61 000 000,Турция,"Турция, Германия, Болгария, Кипр",Türk dili (Türkçe)
19,20,Урду,60 290 000,Пакистан,"Пакистан, Индия","اردو, Urdu"

In [21]:
# вывести последние 7 строк
df_2009.tail(7)

,№,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
61,63,Греческий,12 000 000,Греция,"Греция, Кипр",Ελληνικά
62,64,Чешский,12 000 000,Чехия,Чехия,"Čeština, Česky"
63,65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
64,66,Фула,11 428 700,Западная Африка,Западная Африка,"Pulaar, Fulfulde"
65,67,Дакхни[en],10 709 800,Индия,Индия,NaN
66,68,Малагасийский,10 484 000,Мадагаскар,Мадагаскар,Malagasy
67,69,Белорусский,10 200 000,Белоруссия,"Белоруссия, Польша",Беларуская мова

In [22]:
# вывести список индексов
df_2009.index.tolist()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67]

In [24]:
# вывести список значений колонки Язык
df_2009['Язык'].tolist()

['Китайский',
 'Арабский',
 'Хинди',
 'Английский',
 'Испанский',
 'Бенгальский',
 'Португальский',
 'Русский',
 'Японский',
 'Немецкий',
 'Корейский',
 'Французский',
 'Яванский',
 'Телугу',
 'Маратхи',
 'Вьетнамский',
 'Тамильский',
 'Итальянский',
 'Турецкий',
 'Урду',
 'Панджаби',
 'Украинский',
 'Гуджарати',
 'Тайский',
 'Польский',
 'Малаялам',
 'Каннада',
 'Ория',
 'Бирманский',
 'Азербайджанский',
 'Персидский',
 'Сунданский',
 'Пушту',
 'Румынский',
 'Бходжпури',
 'Хауса',
 'Майтхили',
 'Сербохорватский',
 'Авадхи',
 'Узбекский',
 'Йоруба',
 'Нидерландский',
 'Синдхи',
 'Игбо',
 'Амхарский',
 'Оромо',
 'Индонезийский',
 'Тагальский',
 'Непальский',
 'Ассамский',
 'Сараики',
 'Себуанский',
 'Венгерский',
 'Читтагонг',
 'Чжуанский',
 'Шона',
 'Мадурский',
 'Сингальский',
 'Марвари',
 'Магахи',
 'Харьянви',
 'Греческий',
 'Чешский',
 'Чхаттисгархи',
 'Фула',
 'Дакхни[en]',
 'Малагасийский',
 'Белорусский']

In [25]:
# вывести список наименований колонок
df_2009.columns.tolist()

['№',
 'Язык',
 'Родной язык по версии Encarta[4]',
 'Средоточие',
 'Территории распространения',
 'Самоназвание(образец письменности)']

In [77]:
# вывести строку с номером (№) равным 68=Малагасийский
# (доступ по метке)
df_2009.loc[66]

№                                                68
Язык                                  Малагасийский
Родной язык по версии Encarta[4]         10 484 000
Средоточие                               Мадагаскар
Территории распространения               Мадагаскар
Самоназвание(образец письменности)         Malagasy
Name: 66, dtype: object

In [38]:
# вывести строку с номером (№) равным 68=Малагасийский
# (доступ по числовому значению)
df_2009.iloc[66]

№                                                68
Язык                                  Малагасийский
Родной язык по версии Encarta[4]         10 484 000
Средоточие                               Мадагаскар
Территории распространения               Мадагаскар
Самоназвание(образец письменности)         Malagasy
Name: 66, dtype: object

In [58]:
# вывести dataframe отфильтрованный по условию:
# значение колонки "Средоточие" == "Индия"
df_2009[(df_2009['Средоточие'] == "Индия")]

,№,Язык,Родной язык по версии Encarta[4],Средоточие,Территории распространения,Самоназвание(образец письменности)
2,3,Хинди,366 000 000,Индия,Индия,हिन्दी
13,14,Телугу,69 666 000,Индия,Индия,తెలుగు
14,15,Маратхи,68 022 000,Индия,Индия,मराठी
16,17,Тамильский,66 000 000,Индия,"Индия, Шри-Ланка, Сингапур, Малайзия",தமிழ்
22,23,Гуджарати,46 100 000,Индия,Индия,ગુજરાતી
25,26,Малаялам,35 706 000,Индия,Индия,മലയാളം
26,27,Каннада,35 346 000,Индия,Индия,ಕನ್ನಡ
27,28,Ория,32 300 000,Индия,Индия,ଓଡ଼ିଆ
34,35,Бходжпури,26 254 000,Индия,Индия,भोजपुरी
36,37,Майтхили,24 191 900,Индия,Индия,मैथिली
38,40,Авадхи,20 540 000,Индия,Индия,अवधी
49,51,Ассамский,15 374 000,Индия,Индия,অসমিয়া
58,60,Марвари,13 183 000,Индия,Индия,मारवाड़ी
59,61,Магахи,13 000 000,Индия,Индия,मगही
60,62,Харьянви,13 000 000,Индия,Индия,हरियाणवी
63,65,Чхаттисгархи,11 535 000,Индия,Индия,छत्तिसगढ़ी
65,67,Дакхни[en],10 709 800,Индия,Индия,NaN

In [62]:
# вывести количество уникальных значений в колонке "Средоточие"
df_2009['Средоточие'].nunique()

40

In [63]:
# вывести все уникальные значения в колонке "Средоточие" (тип list)
df_2009['Средоточие'].unique().tolist()

['Китай',
 nan,
 'Индия',
 'Англия',
 'Испания',
 'Бенгалия',
 'Португалия',
 'Россия',
 'Япония',
 'Германия',
 'Корея',
 'Франция',
 'Индонезия',
 'Вьетнам',
 'Италия',
 'Турция',
 'Пакистан',
 'Украина',
 'Таиланд',
 'Польша',
 'Мьянма',
 'Азербайджан',
 'Иран',
 'Афганистан',
 'Румыния',
 'Западная Африка',
 'Сербия, Хорватия',
 'Узбекистан',
 'Нигерия',
 'Нидерланды',
 'Эфиопия',
 'Филиппины',
 'Непал',
 'Венгрия',
 'Бангладеш',
 'Зимбабве',
 'Шри-Ланка',
 'Греция',
 'Чехия',
 'Мадагаскар',
 'Белоруссия']

In [65]:
# переименовать колонку "Родной язык по версии Encarta[4]" на "Родной язык"
df_2009_new = df_2009.rename(columns={'Родной язык по версии Encarta[4]': 'Родной язык'})
# вывести список наименований колонок в датафрейме
df_2009_new.columns.tolist()

['№',
 'Язык',
 'Родной язык',
 'Средоточие',
 'Территории распространения',
 'Самоназвание(образец письменности)']

In [66]:
# получить сведения о датафрейме
# обратить внимание на типы
df_2009_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68 entries, 0 to 67
Data columns (total 6 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   №                                   68 non-null     int64
 1   Язык                                68 non-null     object
 2   Родной язык                         68 non-null     object
 3   Средоточие                          67 non-null     object
 4   Территории распространения          68 non-null     object
 5   Самоназвание(образец письменности)  67 non-null     object
dtypes: int64(1), object(5)
memory usage: 5.8+ KB

In [70]:
# вывести минимальное значение из колонки "Родной язык"
df_2009_new['Родной язык'].min()

'1 212 560 000'

In [71]:
# вывести максимальное значение из колонки "Родной язык"
df_2009_new['Родной язык'].max()

'78 000 000'

Результаты методов `min`/`max` выглядит ожидаемы? Что с ними "так" или "не так"?

Привести свои идеи.

(место для ответа)

Скорее всего всё из-за dtype - object. Не адекватно считывает.

In [78]:
# значения колонки Язык перевести в верхний регистр (большие буквы)
# метод str.upper
df_2009_new['Язык'] = df_2009_new['Язык'].map(str.upper)
# вывести первые 5 и последние 5 значений колонки Язык
# проверить, что регистр изменился
df_2009_new['Язык']

0         КИТАЙСКИЙ
1          АРАБСКИЙ
2             ХИНДИ
3        АНГЛИЙСКИЙ
4         ИСПАНСКИЙ
          ...
63     ЧХАТТИСГАРХИ
64             ФУЛА
65       ДАКХНИ[EN]
66    МАЛАГАСИЙСКИЙ
67      БЕЛОРУССКИЙ
Name: Язык, Length: 68, dtype: object